### ISSUE TITLE
Not adding sensor after installing via HACS

### ISSUE THREAD

**Issue by JVTEAM** [edwork/homeassistant-peloton-sensor#29]
I've installed via HACS and updated configuration.yaml.  I'm not seeing any errors, but it's not populating the sensor.

I've restarted and manually added to files into custom_components as well.

**Comment by tfili** [comment]
I also installed with HACS. No errors and no sensors.

**Comment by edwork** [comment]
Looking into this now, I see this working on my development instance with this as the only loaded integration so I may be testing this in an ideal scenario.  

Were either of you using this prior to it being a default in HACS? If you're able to, add this to your configuration.yaml to show the debug logger messages:  
```
logger:
  logs:
    custom_components.peloton: debug
```

I'm working on cleaning up some additional bugs and should have a new release out soon.

**Comment by tfili** [comment]
It seems to work now but I'm getting some warnings. I feel like when it wasn't working there were more of the same.

`2022-01-05 21:28:59 WARNING (SyncWorker_8) [custom_components.peloton.sensor] Error on parsing State Attributes, something in the API may have changed`

**Comment by tfili** [comment]
These may actually be related to #30

**Comment by JVTEAM** [comment]
I'm still not getting anything to load.  I just put this in on the day I posted this so it was never working before.

**Comment by edwork** [comment]
I just released version 0.7.1 which is far more tolerant of the different workout types and gives more appropriate logging features. I recommend upgrading your installation to 0.7.1 and scanning your log for output. This should create a single entity called `sensor.peloton_<USERNAME>`, and is not yet available to install via the Integrations UI so will not load a card in the UI List of integrations (Yet, coming soon!)

**Comment by JVTEAM** [comment]
Updated and restarted the server.  I'm still not seeing that entity pop in.

**Comment by villasenor** [comment]
So maybe it's just that the sensor is hard to find? I'm not sure if it also wasn't working for me, or if I just wasn't looking hard enough. I thought I was having the same issue - `0.7.1` didn't work, and neither did `0.7.0`. I enabled debug logging and everything and there wasn't anything in the logs with those two versions, and no entities got created (or maybe they did and I missed them). I couldn't get it working until I downgraded to `0.6.0` via HACS which then spit out `Home Assistant Error on parsing State Attributes, something in the API may have changed `, and displayed the sensor. Then, when I upgraded to `0.7.1`, the sensor was still there. I'm running Home Assistant 2021.12.9. So maybe it was there the whole time, or maybe downgrading and upgrading fixed it. Either way, looking forward to having it show up in the Integrations eventually! Great work on this project @edwork!

**Comment by edwork** [comment]
Interesting Timing @villasenor - 

HACS had a bug that was failing to properly clone files ([see this bugfix release](https://github.com/hacs/integration/releases/tag/1.19.3)). Another integration I have been using was failing to load after a recent HACS bug.  

@JVTEAM can you upgrade to HomeAssistant version to 2022.12.9, Upgrade HACS to 1.9.3, make sure your custom_components folder does not have the Peloton folder, restart, and re-install this integration via HACS?

**Comment by JVTEAM** [comment]
Welp...I upgraded and removed the Peloton HACS integration.  Restarted...now I don't see it in the HACS store anymore.

**Comment by edwork** [comment]
@JVTEAM it's been a while, has HACS/This Integration been revitalized?

**Comment by JVTEAM** [comment]
> @JVTEAM it's been a while, has HACS/This Integration been revitalized?

It's still completely missing from the HACS marketplace after upgrading.

**Comment by JVTEAM** [comment]
Well it magically appeared as is now working...who knows
